<?php
session_start();
include_once("../services/auth/seguranca.php");

$produto = array(
    "nome" => "",
    "resumo" => "",
    "descricao" => "",
    "valor" => "",
    "tag" => "",
    "description" => "",
    "arquivo" => "",
    "situacao_id" => "",
    "categoria_id" => ""
);
?>

<div class="container">
	<div class="row">
        <div class="col-md-6">
            <h2>Cadastro de Produto</h2>
        </div>
		<div class="col-md-6 text-end">
			<a href="page.php?link=12" type="button" class="btn btn-primary">
				Voltar
			</a>
		</div>
	</div>

	<div class="row">
		<div class="col-sm-5">
			<form action="../services/produto/cadastra_produto.php" method="post" enctype="multipart/form-data">
				<?php include_once("formulario_produto.phtml");?>
				
				<div class="text-end">
					<button type="submit" class="btn btn-primary btn-block">Cadastrar</button>
				</div>
			</form>
		</div>
	</div>
</div>

<br>