<?php 
session_start();
include_once("../services/auth/seguranca.php");

$id = $_GET['id'];

$result = mysqli_query(
        $GLOBALS['connection'],
        "SELECT * FROM tb_produto WHERE id = '$id' LIMIT 1"
);
$produto = mysqli_fetch_assoc($result);
?> 

<div class="container">
	<div class="row">
        <div class="col-md-6">
            <h2>Editar Produto: <?= $produto['nome'];?></h2>
        </div>
		<div class="col-md-6 text-end">
			<a href="page.php?link=12" type="button" class="btn btn-primary">
				Voltar
			</a>
		</div>
	</div>

	<div class="row">
		<div class="col-sm-6">
			<form action="../services/produto/edita_produto.php" method="post" enctype="multipart/form-data">
				<?php include_once("formulario_produto.phtml");?>

				<input type="hidden" name="id" value="<?= $produto['id'];?>">

				<div class="col-sm-4 col-sm-offset-8">
					<button type="submit" class="btn btn-primary btn-block">Salvar Alterações</button>
				</div>
			</form>
		</div>
	</div>
</div>

<br>