<?php
session_start();
include_once("../services/auth/seguranca.php");

$resultado = mysqli_query($GLOBALS['connection'], "SELECT  * FROM tb_produto ORDER BY id");
$produtos = mysqli_num_rows($resultado);
?>

<div class="container">
    <div class="row">
        <div class="col-md-6">
            <h2>Lista de Produtos</h2>
        </div>
        <div class="col-md-6 text-end">
            <a href="page.php?link=11" class="btn btn-primary">
                <span class="glyphicon glyphicon-plus"></span>
                Novo Produto
            </a>
        </div>
    </div>

	<table class="table">
		<thead>
			<tr>
				<th>ID</th>
				<th>Nome</th>
				<th>Preço</th>
				<th>Situação</th>
				<th>Ações</th>
			</tr>
		</thead>
		<tbody>
			<tr>
				<?php
				while ($produtos = mysqli_fetch_array($resultado)) {
                ?>
				<tr>
				    <td><?= $produtos['id']?></td>
				    <td><?= $produtos['nome']?></td>
				    <td><?= $produtos['id']?></td>
                    <?php
					$situacao_id = $produtos['situacao_id'];
					$result_situacao = mysqli_query($GLOBALS['connection'], "SELECT * FROM tb_situacao");

					while ($dados = mysqli_fetch_assoc($result_situacao)) {
						$id = $dados['id'];

						if($id == $situacao_id){
							echo "<td>" . $dados['nome'] . "</td>";
						}
					}
					?>
					<td>
						<a href="page.php?link=14&id=<?= $produtos['id'];?>" class="btn btn-info btn-sm" type="button">
                            <i class="fas fa-eye"></i>
						</a>

						<a href="page.php?link=13&id=<?= $produtos['id'];?>" class="btn btn-warning btn-sm" type="button">
                            <i class="far fa-edit"></i>
						</a>

						<a href="../services/produto/deleta_produto.php?id=<?= $produtos['id'];?>" class="btn btn-danger btn-sm" type="button">
                            <i class="fas fa-trash"></i>
						</a>
					</td>
                <?php
				}
				?>
			</tr>
		</tbody>
	</table>
</div>
