<?php
session_start();
include_once("../services/auth/seguranca.php");

$usuario = array(
    "nome" => "",
    "email" => "",
    "usuario" => "",
    "senha" => "",
    "nivel_acesso" => ""
);
?>
<div class="container">
    <div class="row">
        <div class="col-md-6">
            <h2>Cadastro de Usuários</h2>
        </div>
        <div class="col-md-6 text-end">
            <a href="page.php?link=2" type="button" class="btn btn-primary">
                Voltar
            </a>
        </div>
    </div>
    <div class="row">
        <div class="col-sm-5">
            <form method="post" action="../services/usuario/cadastra_usuario.php">
                <?php include_once ("formulario_usuario.phtml");?>

                <div class="text-end">
                    <button type="submit" class="btn btn-primary btn-block">Cadastrar</button>
                </div>
            </form>
        </div>
    </div>
</div>
