<?php
session_start();
include_once ("../services/auth/seguranca.php");

$resultado = mysqli_query(
        $GLOBALS['connection'],
        "SELECT  * FROM tb_usuario ORDER BY id"
);

$usuarios = mysqli_num_rows($resultado);
?>

<div class="container">
    <div class="row">
        <div class="col-md-6">
            <h2>Lista de Usuários</h2>
        </div>
        <div class="col-md-6 text-end">
            <a href="page.php?link=3" class="btn btn-primary">
                Novo Usuário
            </a>
        </div>
    </div>

    <div class="row">
        <div class="col-sm-12">
            <table class="table table-condensed">
                <thead>
                    <tr>
                        <th>ID</th>
                        <th>Nome Completo</th>
                        <th>E-mail</th>
                        <th>Usuário</th>
                        <th>Nível de Acesso</th>
                        <th>Ações</th>
                    </tr>
                </thead>
                <tbody>
                    <?php
                    while ($usuarios = mysqli_fetch_array($resultado)) {
                    ?>
                    <tr>
                        <td><?= $usuarios['id'] ?></td>
                        <td><?= $usuarios['nome'] ?></td>
                        <td><?= $usuarios['email'] ?></td>
                        <td><?= $usuarios['usuario'] ?></td>
                        <td><?= $usuarios['nivel_acesso'] ?></td>
                        <td>
                            <a href="page.php?link=5&id=<?= $usuarios['id'];?>" class="btn btn-info btn-sm" type="button">
                                <i class="fas fa-eye"></i>
                            </a>
                            <a href="page.php?link=6&id=<?= $usuarios['id'];?>" class="btn btn-warning btn-sm" type="button">
                                <i class="far fa-edit"></i>
                            </a>
                            <a href="../services/usuario/deleta_usuario.php?id=<?= $usuarios['id'];?>" class="btn btn-danger btn-sm" type="button">
                                <i class="fas fa-trash"></i>
                            </a>
                        </td>
                    </tr>
                    <?php
                    }
                    ?>
                </tbody>
            </table>
        </div>
    </div>
</div>