<?php
session_start();
include_once ("../services/auth/seguranca.php");

$id = $_GET['id'];

$resultado = mysqli_query($GLOBALS['connection'], "SELECT * FROM tb_usuario WHERE id = '$id'  LIMIT 1");
$usuario = mysqli_fetch_assoc($resultado);
?>

<div class="container">
    <div class="row">
        <div class="col-md-6">
            <h2>Usuário: <?= $usuario['nome'];?></h2>
        </div>

        <div class="col-md-6 text-end">
            <a href="page.php?link=2" type="button" class="btn btn-info">Lista de Usuários</a>

            <a href="page.php?link=6&id=<?= $usuario['id'];?>" type="button" class="btn btn-warning">
                <i class="far fa-edit"></i>
            </a>

            <a href="../services/usuario/deleta_usuario.php?id=<?= $usuario['id'];?>" type="button" class="btn btn-danger">
                <i class="fas fa-trash"></i>
            </a>
        </div>
    </div>

    <br>

    <div class="row">
        <div class="col-sm-12">
            <table class="table">
                <thead>
                    <tr>
                        <th>ID</th>
                        <th>E-mail</th>
                        <th>Usuário</th>
                        <th>Nível de Acesso</th>
                        <th>Data Criação</th>
                        <th>Data Modificação</th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td><?= $usuario['id'];?></td>
                        <td><?= $usuario['email'];?></td>
                        <td><?= $usuario['usuario'];?></td>
                        <td><?= $usuario['nivel_acesso'];?></td>
                        <td><?= date("d/m/Y", strtotime($usuario['criado']));?></td>
                        <td><?= date("d/m/Y", strtotime($usuario['modificado']));?></td>
                    </tr>
                </tbody>
            </table>
        </div>
    </div>
</div>
