<?php
session_start();
include_once("../services/auth/seguranca.php");

$id = $_GET['id'];

$result = mysqli_query($GLOBALS['connection'], "SELECT * FROM tb_categoria WHERE id = '$id' LIMIT 1");
$categoria = mysqli_fetch_assoc($result);
?>

<div class="container">
    <div class="row">
        <div class="col-md-6">
            <h2>Editar Categoria: <?= $categoria['nome']?></h2>
        </div>
        <div class="col-md-6 text-end">
            <a href="page.php?link=8" class="btn btn-primary">
                Voltar
            </a>
        </div>
    </div>

    <div class="row">
        <div class="col-md-5">
            <form action="../services/categoria/edita_categoria.php" class="form-horizontal" method="post">
                <div class="mb-3">
                    <label for="" class="form-label">Nome Categoria</label>
                    <input type="text" class="form-control" name="nome" placeholder="Nome Categoria" value="<?= $categoria['nome']?>">
                </div>

                <input type="hidden" name="id" value="<?= $categoria['id'];?>">

                <div class="text-end">
                    <button type="submit" class="btn btn-primary btn-block">Salvar</button>
                </div>
            </form>
        </div>
    </div>
</div>

