<?php 
session_start();
include_once ("../services/auth/seguranca.php");

$resultado = mysqli_query($GLOBALS['connection'], "SELECT * FROM tb_categoria ORDER BY id");
$categorias = mysqli_num_rows($resultado);
?>

<div class="container">
    <div class="row">
        <div class="col-md-6">
            <h2>Lista de Categorias</h2>
        </div>
        <div class="col-md-6 text-end">
            <a href="page.php?link=7" class="btn btn-primary">
                Nova Categoria
            </a>
        </div>
    </div>

    <div class="row">
        <div class="col-sm-12">
            <table class="table table-condensed">
                <thead>
                    <tr>
                        <th>Categoria</th>
                        <th>Ações</th>
                    </tr>
                </thead>
                <tbody>
                    <?php
                    while($categorias = mysqli_fetch_array($resultado)){
                    ?>
                    <tr>
                        <td><?= $categorias['nome']?></td>
                        <td>
                            <a href="page.php?link=10&id=<?= $categorias['id']?>" class="btn btn-info btn-sm" type="button">
                                <i class="fas fa-eye"></i>
                            </a>

                            <a href="page.php?link=9&id=<?= $categorias['id']?>" class="btn btn-warning btn-sm" type="button">
                                <i class="far fa-edit"></i>
                            </a>

                            <a href="../services/categoria/deleta_categoria.php?id=<?= $categorias['id'];?>" class="btn btn-danger btn-sm" type="button">
                                <i class="fas fa-trash"></i>
                            </a>
                        </td>
                    </tr>
                    <?php
                    }
                    ?>
                </tbody>
            </table>
        </div>
    </div>

</div>