<?php
session_start();
include_once ("../services/auth/seguranca.php");

$id = $_GET['id'];

$resultado = mysqli_query($GLOBALS['connection'], "SELECT * FROM tb_categoria WHERE id = '$id'  LIMIT 1");
$categoria = mysqli_fetch_assoc($resultado);
?>

<div class="container">
    <div class="row">
        <div class="col-md-6">
            <h2>Categoria: <?= $categoria['nome'];?></h2>
        </div>

        <div class="col-md-6 text-end">
            <a href="page.php?link=8" type="button" class="btn btn-info">Lista de Categorias</a>

            <a href="page.php?link=9&id=<?= $categoria['id'];?>" type="button" class="btn btn-warning">
                <i class="far fa-edit"></i>
            </a>

            <a href="../services/categoria/deleta_categoria.php?id=<?= $categoria['id'];?>" type="button" class="btn btn-danger">
                <i class="fas fa-trash"></i>
            </a>
        </div>
    </div>

    <table class="table">
    	<thead>
    		<tr>
    			<th>ID</th>
    			<th>Nome</th>
                <th>Data Criação</th>
                <th>Data Modificação</th>
    		</tr>
    	</thead>
    	<tbody>
    		<tr>
    			<td><?= $categoria['id']?></td>
    			<td><?= $categoria['nome']?></td>
                <td><?= date("d/m/Y", strtotime($categoria['criado']));?></td>
                <td><?= date("d/m/Y", strtotime($categoria['modificado']));?></td>
    		</tr>
    	</tbody>
    </table>