<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="Página área restrita">
    <link rel="icon" href="">

    <title>Área Restrita</title>

    <script src="https://use.fontawesome.com/releases/v5.15.3/js/all.js" crossorigin="anonymous"></script>
    <link href="https://fonts.googleapis.com/css?family=Catamaran:100,200,300,400,500,600,700,800,900" rel="stylesheet" />
    <link href="https://fonts.googleapis.com/css?family=Lato:100,100i,300,300i,400,400i,700,700i,900,900i" rel="stylesheet" />
    <link href="../../../assets/css/styles.css" rel="stylesheet" />
    <link href="../../../assets/css/site.css" rel="stylesheet" />
    <link href="../../../assets/css/dashboard.css" rel="stylesheet" />
    <link href="../../../assets/css/toastr.min.css" rel="stylesheet" />
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top navbar-expand-lg ">
        <div class="container-fluid">
            <a class="navbar-brand" href="page.php?link=1">
                Área Restrita
            </a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse justify-content-end" id="navbarNavDropdown">
                <ul class="navbar-nav">
                    <li class="nav-item">
                        <a class="nav-link" href="page.php?link=2">
                            <i class="fas fa-users"></i>
                            Usuários
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="page.php?link=12">
                            <i class="fab fa-product-hunt"></i>
                            Produtos
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="page.php?link=8">
                            <i class="fas fa-list"></i>
                            Categorias
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="page.php?link=15">
                            <i class="far fa-bookmark"></i>
                            Status
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="../services/auth/logout.php">
                            <i class="fas fa-sign-out-alt"></i>
                            Sair
                        </a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>