<?php
session_start();
include_once("../services/auth/seguranca.php");
?>

<div class="container">
    <div class="row">
        <div class="col-md-6">
            <h2>Cadastrar Status</h2>
        </div>
        <div class="col-md-6 text-end">
            <a href="page.php?link=15" class="btn btn-primary">
                Voltar
            </a>
        </div>
    </div>

    <div class="row">
        <div class="col-md-5">
            <form action="../services/situacao/cadastra_situacao.php" class="form-horizontal" method="post">
                <div class="mb-3">
                    <label class="form-label">Nome Status</label>
                    <input type="text" class="form-control" name="nome" placeholder="Nome Status">
                </div>

                <div class="text-end">
                    <button type="submit" class="btn btn-primary btn-block">Salvar</button>
                </div>
            </form>
        </div>
    </div>
</div>

