<?php 
session_start();
include_once ("../services/auth/seguranca.php");

$resultado = mysqli_query(
        $GLOBALS['connection'],
        "SELECT * FROM tb_situacao ORDER BY id"
);
$situacoes = mysqli_num_rows($resultado);
?>

<div class="container">
    <div class="row">
        <div class="col-md-6">
            <h2>Lista de Status</h2>
        </div>
        <div class="col-md-6 text-end">
            <a href="page.php?link=16" class="btn btn-primary">
                Novo Usuário
            </a>
        </div>
    </div>

    <div class="row">
        <div class="col-sm-12">
            <table class="table table-condensed">
                <thead>
                    <tr>
                        <th>Situação</th>
                        <th>Ações</th>
                    </tr>
                </thead>
                <tbody>
                    <?php
                    while ($situacoes = mysqli_fetch_array($resultado)) {
                    ?>
                    <tr>
                        <td>
                            <?= $situacoes['nome']?>
                        </td>
                        <td>
                            <a href="page.php?link=18&id=<?php echo $situacoes['id']?>" class="btn btn-info btn-sm" type="button">
                                <i class="fas fa-eye"></i>
                            </a>

                            <a href="page.php?link=17&id=<?php echo $situacoes['id']?>" class="btn btn-warning btn-sm" type="button">
                                <i class="far fa-edit"></i>
                            </a>

                            <a href="../services/situacao/deleta_situacao.php?id=<?php echo $situacoes['id'];?>" class="btn btn-danger btn-sm" type="button">
                                <i class="fas fa-trash"></i>
                            </a>
                        </td>
                    </tr>
                    <?php
                    }
                    ?>
                </tbody>
            </table>
        </div>
    </div>
</div>