<?php
session_start();
include_once ("../services/auth/seguranca.php");

$id = $_GET['id'];

$resultado = mysqli_query(
        $GLOBALS['connection'],
        "SELECT * FROM tb_situacao WHERE id = '$id'  LIMIT 1"
);

$situacao = mysqli_fetch_assoc($resultado);
?>

<div class="container">
    <div class="row">
        <div class="col-md-6">
            <h2>Status: <?= $situacao['nome'];?></h2>
        </div>

        <div  class="col-md-6 text-end">
            <a href="page.php?link=15" type="button" class="btn btn-info">Listar Situações</a>

            <a href="page.php?link=17&id=<?= $situacao['id'];?>" type="button" class="btn btn-warning">
                <i class="far fa-edit"></i>
            </a>

            <a href="../services/situacao/deleta_situacao.php?id=<?= $situacao['id'];?>" type="button" class="btn btn-danger">
                <i class="fas fa-trash"></i>
            </a>
        </div>
    </div>

    <table class="table">
    	<thead>
    		<tr>
    			<th>ID</th>
    			<th>Nome</th>
    			<th>Data Criação</th>
    			<th>Data Modificação</th>
    		</tr>
    	</thead>
    	<tbody>
    		<tr>
    			<td><?= $situacao['id']?></td>
    			<td><?= $situacao['nome']?></td>
    			<td><?= date("d/m/Y", strtotime($situacao['criado']));?></td>
    			<td><?= date("d/m/Y", strtotime($situacao['modificado']));?></td>
    		</tr>
    	</tbody>
    </table>